### ISSUE TITLE
Not working on hyprland

### ISSUE THREAD

**Issue by glyh** [rvaiya/warp#252]
When I tried `warpd --hint`, it says:
```
[destroyed object]: error 4: surface was destroyed before its role object
```

**Comment by rijkvp** [comment]
I get the same error with Hyprland on NixOS. But the program also hangs and consumes 100% CPU which seems related to #214.

**Comment by rat857** [comment]
![image](https://github.com/rvaiya/warpd/assets/76930631/c2a0bf5d-0f80-4a18-8731-1b886107054e)

**Comment by rat857** [comment]
@glyh me too
![image](https://github.com/rvaiya/warpd/assets/76930631/358cbeb0-d3ca-4289-ab4a-0a95f0bb402e)

**Comment by kkoyung** [comment]
> I get the same error with Hyprland on NixOS. But the program also hangs and consumes 100% CPU which seems related to #214.

Same situation with Sway on ArchLinux.

warpd: v1.3.5 (built from: 5d27d1c) (installed via AUR package warpd)
sway: v1.9-dev-bbabb9aa (installed via AUR package sway-git)
archlinux: 6.6.7-arch1-1

**Comment by vincentaxhe** [comment]
did not work in hyprland with hyprland-portal which I prefer

**Comment by LovesTha** [comment]
I too am getting this error in Hyprland + NixOS

I spun up sway briefly to test in there and warpd works fine, so it's most likely a hyprland issue, although it could be something about how I have hyprland configured.

**Comment by LovesTha** [comment]
I too am getting this error in Hyprland + NixOS

I spun up sway briefly to test in there and warpd works fine, so it's most likely a hyprland issue, although it could be something about how I have hyprland configured but as a bare config errors with permission errors it's hard to figure out what minimal config would be best to test against.

**Comment by abhinav3398** [comment]
I don't know about nixos (since Arch btw) but, Have you tried building/installing after setting environment variable that disables building for X(DISABLE_X)?

I was banging my head for 2 days until I tried this, and it worked.

**Comment by anpandey** [comment]
Using this overlay to override to the latest commit on NixOS worked for me:

```nix
nixpkgs.overlays = [
  (self: super: {
    warpd = (super.warpd.overrideAttrs (old: {
      src = super.fetchFromGitHub {
        owner = "rvaiya";
        repo = "warpd";
        rev = "01650eabf70846deed057a77ada3c0bbb6d97d6e";
        sha256 = "sha256-61+kJvOi4oog0+tGucc1rWemdx2vp15wlluJE+1PzTs=";
      };
    })).override{withX = false;};
  })
];
```
I suspect the pinned version in nixpkgs might be broken.

**Comment by sonjiku** [comment]
> Using this overlay to override to the latest commit on NixOS worked for me:
> 
> ```nix
> nixpkgs.overlays = [
>   (self: super: {
>     warpd = (super.warpd.overrideAttrs (old: {
>       src = super.fetchFromGitHub {
>         owner = "rvaiya";
>         repo = "warpd";
>         rev = "01650eabf70846deed057a77ada3c0bbb6d97d6e";
>         sha256 = "sha256-61+kJvOi4oog0+tGucc1rWemdx2vp15wlluJE+1PzTs=";
>       };
>     })).override{withX = false;};
>   })
> ];
> ```
> 
> I suspect the pinned version in nixpkgs might be broken.

I did this and it worked fine for a while, but now after reloading sway, the binds don't work, and when running on terminal i get this with every mode:
```
┗━❱ warpd -f
Starting warpd v1.3.5
warpd: src/platform/linux/wayland/wl.c:28: handle_global: Assertion `!wl.seat' failed.
Aborted (core dumped)
```

Passing $WAYLAND_DEBUG=1 on a fresh sway login getts me this:
```
┗━❱ WAYLAND_DEBUG=1 warpd --hint
[2383401.798] {Default Queue}  -> wl_display#1.get_registry(new id wl_registry#2)
[2383401.953] {Default Queue} wl_registry#2.global(1, "wl_shm", 1)
[2383401.968] {Default Queue}  -> wl_registry#2.bind(1, "wl_shm", 1, new id [unknown]#3)
[2383401.979] {Default Queue} wl_registry#2.global(2, "wl_drm", 2)
[2383401.988] {Default Queue} wl_registry#2.global(3, "zwp_linux_dmabuf_v1", 4)
[2383401.995] {Default Queue} wl_registry#2.global(4, "wl_compositor", 6)
[2383402.011] {Default Queue}  -> wl_registry#2.bind(4, "wl_compositor", 4, new id [unknown]#4)
[2383402.019] {Default Queue} wl_registry#2.global(5, "wl_subcompositor", 1)
[2383402.027] {Default Queue} wl_registry#2.global(6, "wl_data_device_manager", 3)
[2383402.033] {Default Queue} wl_registry#2.global(7, "zwlr_gamma_control_manager_v1", 1)
[2383402.041] {Default Queue} wl_registry#2.global(8, "zxdg_output_manager_v1", 3)
[2383402.049] {Default Queue}  -> wl_registry#2.bind(8, "zxdg_output_manager_v1", 3, new id [unknown]#5)
[2383402.056] {Default Queue} wl_registry#2.global(9, "ext_idle_notifier_v1", 1)
[2383402.063] {Default Queue} wl_registry#2.global(10, "zwp_idle_inhibit_manager_v1", 1)
[2383402.070] {Default Queue} wl_registry#2.global(11, "zwlr_layer_shell_v1", 4)
[2383402.077] {Default Queue}  -> wl_registry#2.bind(11, "zwlr_layer_shell_v1", 2, new id [unknown]#6)
[2383402.085] {Default Queue} wl_registry#2.global(12, "xdg_wm_base", 2)
[2383402.092] {Default Queue} wl_registry#2.global(13, "zwp_tablet_manager_v2", 1)
[2383402.099] {Default Queue} wl_registry#2.global(14, "org_kde_kwin_server_decoration_manager", 1)
[2383402.105] {Default Queue} wl_registry#2.global(15, "zxdg_decoration_manager_v1", 1)
[2383402.111] {Default Queue} wl_registry#2.global(16, "zwp_relative_pointer_manager_v1", 1)
[2383402.118] {Default Queue} wl_registry#2.global(17, "zwp_pointer_constraints_v1", 1)
[2383402.125] {Default Queue} wl_registry#2.global(18, "wp_presentation", 1)
[2383402.131] {Default Queue} wl_registry#2.global(19, "zwlr_output_manager_v1", 4)
[2383402.138] {Default Queue} wl_registry#2.global(20, "zwlr_output_power_manager_v1", 1)
[2383402.144] {Default Queue} wl_registry#2.global(21, "zwp_input_method_manager_v2", 1)
[2383402.152] {Default Queue} wl_registry#2.global(22, "zwp_text_input_manager_v3", 1)
[2383402.159] {Default Queue} wl_registry#2.global(23, "zwlr_foreign_toplevel_manager_v1", 3)
[2383402.166] {Default Queue} wl_registry#2.global(24, "ext_session_lock_manager_v1", 1)
[2383402.173] {Default Queue} wl_registry#2.global(25, "wp_drm_lease_device_v1", 1)
[2383402.178] {Default Queue} wl_registry#2.global(26, "zwlr_export_dmabuf_manager_v1", 1)
[2383402.184] {Default Queue} wl_registry#2.global(27, "zwlr_screencopy_manager_v1", 3)
[2383402.191] {Default Queue} wl_registry#2.global(28, "zwlr_data_control_manager_v1", 2)
[2383402.198] {Default Queue} wl_registry#2.global(29, "wp_security_context_manager_v1", 1)
[2383402.204] {Default Queue} wl_registry#2.global(30, "wp_viewporter", 1)
[2383402.211] {Default Queue} wl_registry#2.global(31, "wp_single_pixel_buffer_manager_v1", 1)
[2383402.219] {Default Queue} wl_registry#2.global(32, "wp_content_type_manager_v1", 1)
[2383402.226] {Default Queue} wl_registry#2.global(33, "wp_fractional_scale_manager_v1", 1)
[2383402.233] {Default Queue} wl_registry#2.global(34, "zxdg_exporter_v1", 1)
[2383402.240] {Default Queue} wl_registry#2.global(35, "zxdg_importer_v1", 1)
[2383402.245] {Default Queue} wl_registry#2.global(36, "zxdg_exporter_v2", 1)
[2383402.252] {Default Queue} wl_registry#2.global(37, "zxdg_importer_v2", 1)
[2383402.259] {Default Queue} wl_registry#2.global(38, "xdg_activation_v1", 1)
[2383402.266] {Default Queue} wl_registry#2.global(39, "wp_cursor_shape_manager_v1", 1)
[2383402.273] {Default Queue} wl_registry#2.global(40, "zwp_virtual_keyboard_manager_v1", 1)
[2383402.280] {Default Queue} wl_registry#2.global(41, "zwlr_virtual_pointer_manager_v1", 2)
[2383402.287] {Default Queue}  -> wl_registry#2.bind(41, "zwlr_virtual_pointer_manager_v1", 1, new id [unknown]#7)
[2383402.297] {Default Queue}  -> zwlr_virtual_pointer_manager_v1#7.create_virtual_pointer(nil, new id zwlr_virtual_pointer_v1#8)
[2383402.307] {Default Queue} wl_registry#2.global(42, "zwlr_input_inhibit_manager_v1", 1)
[2383402.316] {Default Queue} wl_registry#2.global(43, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[2383402.325] {Default Queue} wl_registry#2.global(44, "zwp_pointer_gestures_v1", 3)
[2383402.335] {Default Queue} wl_registry#2.global(45, "wl_seat", 8)
[2383402.349] {Default Queue}  -> wl_registry#2.bind(45, "wl_seat", 7, new id [unknown]#9)
[2383402.360] {Default Queue}  -> wl_seat#9.get_keyboard(new id wl_keyboard#10)
[2383402.372] {Default Queue} wl_registry#2.global(47, "zwp_primary_selection_device_manager_v1", 1)
[2383402.380] {Default Queue} wl_registry#2.global(48, "wl_output", 4)
[2383402.391] {Default Queue}  -> wl_registry#2.bind(48, "wl_output", 3, new id [unknown]#11)
[2383402.402] {Default Queue}  -> zxdg_output_manager_v1#5.get_xdg_output(new id zxdg_output_v1#12, wl_output#11)
[2383402.559] {Default Queue} discarded wl_shm#3.format(0)
[2383402.581] {Default Queue} discarded wl_shm#3.format(1)
[2383402.589] {Default Queue} discarded wl_shm#3.format(875709016)
[2383402.595] {Default Queue} discarded wl_shm#3.format(875708993)
[2383402.601] {Default Queue} discarded wl_shm#3.format(875710274)
[2383402.608] {Default Queue} discarded wl_shm#3.format(842094674)
[2383402.615] {Default Queue} discarded wl_shm#3.format(842088786)
[2383402.621] {Default Queue} discarded wl_shm#3.format(892426322)
[2383402.627] {Default Queue} discarded wl_shm#3.format(892420434)
[2383402.635] {Default Queue} discarded wl_shm#3.format(909199186)
[2383402.642] {Default Queue} discarded wl_shm#3.format(808665688)
[2383402.648] {Default Queue} discarded wl_shm#3.format(808665665)
[2383402.654] {Default Queue} discarded wl_shm#3.format(1211384408)
[2383402.661] {Default Queue} discarded wl_shm#3.format(1211384385)
[2383402.667] {Default Queue} discarded wl_shm#3.format(942948952)
[2383402.673] {Default Queue} discarded wl_shm#3.format(942948929)
[2383402.680] {Default Queue} discarded wl_seat#9.name("seat0")
[2383402.686] {Default Queue} discarded wl_seat#9.capabilities(3)
[2383402.693] {Default Queue} wl_keyboard#10.keymap(1, fd 4, 73065)
[2383407.620] {Default Queue} wl_keyboard#10.repeat_info(25, 200)
[2383407.675] {Default Queue} discarded wl_output#11.geometry(0, 0, 310, 170, 0, "Chimei Innolux Corporation", "0x14FF", 0)
[2383407.691] {Default Queue} discarded wl_output#11.mode(1, 1920, 1080, 60008)
[2383407.702] {Default Queue} discarded wl_output#11.scale(1)
[2383407.709] {Default Queue} discarded wl_output#11.done()
[2383407.716] {Default Queue} zxdg_output_v1#12.name("eDP-1")
[2383407.723] {Default Queue} zxdg_output_v1#12.description("Chimei Innolux Corporation 0x14FF (eDP-1)")
[2383407.731] {Default Queue} zxdg_output_v1#12.logical_position(0, 0)
[2383407.739] {Default Queue} zxdg_output_v1#12.logical_size(1920, 1080)
[2383407.746] {Default Queue} discarded wl_output#11.done()
[2383409.998] {Default Queue}  -> wl_shm#3.create_pool(new id wl_shm_pool#13, fd 6, 8302080)
[2383410.090] {Default Queue}  -> wl_seat#9.get_pointer(new id wl_pointer#14)
[2383410.110] {Default Queue}  -> wl_shm_pool#13.create_buffer(new id wl_buffer#15, 0, 1920, 1080, 7680, 0)
[2383410.127] {Default Queue}  -> wl_compositor#4.create_surface(new id wl_surface#16)
[2383410.139] {Default Queue}  -> zwlr_layer_shell_v1#6.get_layer_surface(new id zwlr_layer_surface_v1#17, wl_surface#16, wl_output#11, 3, "warpd")
[2383410.153] {Default Queue}  -> zwlr_layer_surface_v1#17.set_size(10, 10)
[2383410.163] {Default Queue}  -> zwlr_layer_surface_v1#17.set_anchor(5)
[2383410.174] {Default Queue}  -> zwlr_layer_surface_v1#17.set_margin(0, 0, 0, 0)
[2383410.184] {Default Queue}  -> zwlr_layer_surface_v1#17.set_exclusive_zone(-1)
[2383410.195] {Default Queue}  -> wl_surface#16.commit()
[2383410.218] {Default Queue}  -> zwlr_virtual_pointer_v1#8.motion(0, 1.00000000, 1.00000000)
[2383410.398] {Default Queue} discarded wl_surface#16.enter(wl_output#11)
[2383410.408] {Default Queue} zwlr_layer_surface_v1#17.configure(149, 10, 10)
[2383410.418] {Default Queue}  -> zwlr_layer_surface_v1#17.ack_configure(149)
[2383410.427] {Default Queue}  -> wl_surface#16.attach(wl_buffer#15, 0, 0)
[2383410.436] {Default Queue}  -> wl_surface#16.commit()
[2383410.444] {Default Queue} zwlr_layer_surface_v1#17.configure(153, 10, 10)
[2383410.456] {Default Queue}  -> zwlr_layer_surface_v1#17.ack_configure(153)
[2383410.463] {Default Queue}  -> wl_surface#16.attach(wl_buffer#15, 0, 0)
[2383410.474] {Default Queue}  -> wl_surface#16.commit()
[2383410.482] {Default Queue}  -> zwlr_virtual_pointer_v1#8.motion(0, 1.00000000, 1.00000000)
[2383425.800] {Default Queue} wl_pointer#14.enter(156, wl_surface#16, 326.75000000, 553.75000000)
[2383425.881] {Default Queue} wl_pointer#14.frame()
[2383425.890] {Default Queue} zwlr_layer_surface_v1#17.configure(159, 10, 10)
[2383425.902] {Default Queue}  -> zwlr_layer_surface_v1#17.ack_configure(159)
[2383425.919] {Default Queue}  -> wl_surface#16.attach(wl_buffer#15, 0, 0)
[2383425.934] {Default Queue}  -> wl_surface#16.commit()
[2383425.944] {Default Queue} discarded wl_buffer#15.release()
[2383425.956] {Default Queue} discarded wl_buffer#15.release()
[2383425.967] {Default Queue} wl_pointer#14.motion(0, 327.75000000, 554.75000000)
[2383425.979] {Default Queue}  -> zwlr_layer_surface_v1#17.destroy()
[2383425.991] {Default Queue}  -> wl_surface#16.destroy()
[2383426.005] {Default Queue}  -> wl_buffer#15.destroy()
[2383503.293] {Default Queue}  -> wl_shm_pool#13.create_buffer(new id wl_buffer#18, 0, 1920, 1080, 7680, 0)
[2383503.319] {Default Queue}  -> wl_compositor#4.create_surface(new id wl_surface#19)
[2383503.329] {Default Queue}  -> zwlr_layer_shell_v1#6.get_layer_surface(new id zwlr_layer_surface_v1#20, wl_surface#19, wl_output#11, 3, "warpd")
[2383503.340] {Default Queue}  -> zwlr_layer_surface_v1#20.set_size(10, 10)
[2383503.346] {Default Queue}  -> zwlr_layer_surface_v1#20.set_anchor(5)
[2383503.354] {Default Queue}  -> zwlr_layer_surface_v1#20.set_margin(0, 0, 0, 0)
[2383503.362] {Default Queue}  -> zwlr_layer_surface_v1#20.set_exclusive_zone(-1)
[2383503.374] {Default Queue}  -> wl_surface#19.commit()
[2383503.385] {Default Queue}  -> wl_shm_pool#13.create_buffer(new id wl_buffer#21, 0, 1, 1, 7680, 0)
[2383503.396] {Default Queue}  -> wl_compositor#4.create_surface(new id wl_surface#22)
[2383503.412] {Default Queue}  -> zwlr_layer_shell_v1#6.get_layer_surface(new id zwlr_layer_surface_v1#23, wl_surface#22, wl_output#11, 3, "warpd")
[2383503.426] {Default Queue}  -> zwlr_layer_surface_v1#23.set_size(10, 10)
[2383503.435] {Default Queue}  -> zwlr_layer_surface_v1#23.set_anchor(5)
[2383503.447] {Default Queue}  -> zwlr_layer_surface_v1#23.set_margin(0, 0, 0, 0)
[2383503.457] {Default Queue}  -> zwlr_layer_surface_v1#23.set_exclusive_zone(-1)
[2383503.465] {Default Queue}  -> zwlr_layer_surface_v1#23.set_keyboard_interactivity(1)
[2383503.474] {Default Queue}  -> wl_surface#22.commit()
[2383504.196] discarded [unknown]#15.[event 0](0 fd, 8 byte)
[2383504.217] {Display Queue} wl_display#1.delete_id(17)
[2383504.249] {Display Queue} wl_display#1.delete_id(16)
[2383504.259] {Display Queue} wl_display#1.delete_id(15)
[2383504.271] {Default Queue} wl_pointer#14.leave(165, nil)
[2383504.284] {Default Queue} wl_pointer#14.frame()
[2383504.291] {Default Queue} discarded wl_surface#19.enter(wl_output#11)
[2383504.298] {Default Queue} zwlr_layer_surface_v1#20.configure(168, 10, 10)
[2383504.307] {Default Queue}  -> zwlr_layer_surface_v1#20.ack_configure(168)
[2383504.339] {Default Queue}  -> wl_surface#19.attach(wl_buffer#18, 0, 0)
[2383504.349] {Default Queue}  -> wl_surface#19.commit()
[2383504.358] {Default Queue} zwlr_layer_surface_v1#20.configure(172, 10, 10)
[2383504.366] {Default Queue}  -> zwlr_layer_surface_v1#20.ack_configure(172)
[2383504.379] {Default Queue}  -> wl_surface#19.attach(wl_buffer#18, 0, 0)
[2383504.388] {Default Queue}  -> wl_surface#19.commit()
[2383504.395] {Default Queue} discarded wl_surface#22.enter(wl_output#11)
[2383504.404] {Default Queue} zwlr_layer_surface_v1#23.configure(176, 10, 10)
[2383504.413] {Default Queue}  -> zwlr_layer_surface_v1#23.ack_configure(176)
[2383504.420] {Default Queue}  -> wl_surface#22.attach(wl_buffer#21, 0, 0)
[2383504.428] {Default Queue}  -> wl_surface#22.commit()
[2383504.435] {Default Queue} zwlr_layer_surface_v1#20.configure(177, 10, 10)
[2383504.443] {Default Queue}  -> zwlr_layer_surface_v1#20.ack_configure(177)
[2383504.451] {Default Queue}  -> wl_surface#19.attach(wl_buffer#18, 0, 0)
[2383504.459] {Default Queue}  -> wl_surface#19.commit()
[2383504.465] {Default Queue} zwlr_layer_surface_v1#23.configure(181, 10, 10)
[2383504.474] {Default Queue}  -> zwlr_layer_surface_v1#23.ack_configure(181)
[2383504.482] {Default Queue}  -> wl_surface#22.attach(wl_buffer#21, 0, 0)
[2383504.490] {Default Queue}  -> wl_surface#22.commit()
[2383504.497] {Default Queue} zwlr_layer_surface_v1#20.configure(182, 10, 10)
[2383504.506] {Default Queue}  -> zwlr_layer_surface_v1#20.ack_configure(182)
[2383504.513] {Default Queue}  -> wl_surface#19.attach(wl_buffer#18, 0, 0)
[2383504.521] {Default Queue}  -> wl_surface#19.commit()
[2383507.917] {Default Queue} wl_pointer#14.enter(184, wl_surface#19, 327.75000000, 554.75000000)
[2383507.947] {Default Queue} wl_pointer#14.frame()
[2383507.959] {Default Queue} zwlr_layer_surface_v1#23.configure(187, 10, 10)
[2383507.969] {Default Queue}  -> zwlr_layer_surface_v1#23.ack_configure(187)
[2383507.977] {Default Queue}  -> wl_surface#22.attach(wl_buffer#21, 0, 0)
[2383507.986] {Default Queue}  -> wl_surface#22.commit()
[2383507.995] {Default Queue} zwlr_layer_surface_v1#20.configure(188, 10, 10)
[2383508.002] {Default Queue}  -> zwlr_layer_surface_v1#20.ack_configure(188)
[2383508.009] {Default Queue}  -> wl_surface#19.attach(wl_buffer#18, 0, 0)
[2383508.041] {Default Queue}  -> wl_surface#19.commit()
[2383508.052] {Default Queue} discarded wl_buffer#18.release()
[2383508.058] {Default Queue} discarded wl_buffer#18.release()
[2383508.065] {Default Queue} zwlr_layer_surface_v1#23.configure(192, 10, 10)
[2383508.072] {Default Queue}  -> zwlr_layer_surface_v1#23.ack_configure(192)
[2383508.080] {Default Queue}  -> wl_surface#22.attach(wl_buffer#21, 0, 0)
[2383508.088] {Default Queue}  -> wl_surface#22.commit()
[2383508.099] {Default Queue} zwlr_layer_surface_v1#20.configure(193, 10, 10)
[2383508.112] {Default Queue}  -> zwlr_layer_surface_v1#20.ack_configure(193)
[2383508.119] {Default Queue}  -> wl_surface#19.attach(wl_buffer#18, 0, 0)
[2383508.127] {Default Queue}  -> wl_surface#19.commit()
[2383508.135] {Default Queue} wl_keyboard#10.enter(197, wl_surface#22, array[0])
[2383508.143] {Default Queue} wl_keyboard#10.modifiers(198, 0, 0, 16, 0)
[2383508.153] {Default Queue} discarded wl_buffer#21.release()
[2383508.159] {Default Queue} discarded wl_buffer#18.release()
[2383508.167] {Default Queue} discarded wl_buffer#21.release()
[2383508.174] {Default Queue} discarded wl_buffer#18.release()
wayland: mouse hiding not implemented
[2383508.281] {Default Queue} discarded wl_buffer#21.release()
[2383508.291] {Default Queue} discarded wl_buffer#18.release()
[2383508.298] {Default Queue} discarded wl_buffer#21.release()
[2383508.306] {Default Queue} discarded wl_buffer#18.release()
[2387818.721] {Default Queue} wl_keyboard#10.key(199, 81834245, 1, 1)
[2387818.763] {Default Queue} wl_keyboard#10.key(200, 81834245, 1, 0)
[2387818.793] {Default Queue}  -> zwlr_layer_surface_v1#23.destroy()
[2387818.809] {Default Queue}  -> wl_surface#22.destroy()
[2387818.823] {Default Queue}  -> wl_buffer#21.destroy()
[2387818.836] {Default Queue}  -> zwlr_layer_surface_v1#20.destroy()
[2387818.848] {Default Queue}  -> wl_surface#19.destroy()
[2387818.861] {Default Queue}  -> wl_buffer#18.destroy()
```

And after 1 reload:

```
┗━❱ WAYLAND_DEBUG=1 warpd --hint
[2429760.998] {Default Queue}  -> wl_display#1.get_registry(new id wl_registry#2)
[2429761.312] {Default Queue} wl_registry#2.global(1, "wl_shm", 1)
[2429761.326] {Default Queue}  -> wl_registry#2.bind(1, "wl_shm", 1, new id [unknown]#3)
[2429761.337] {Default Queue} wl_registry#2.global(2, "wl_drm", 2)
[2429761.345] {Default Queue} wl_registry#2.global(3, "zwp_linux_dmabuf_v1", 4)
[2429761.354] {Default Queue} wl_registry#2.global(4, "wl_compositor", 6)
[2429761.368] {Default Queue}  -> wl_registry#2.bind(4, "wl_compositor", 4, new id [unknown]#4)
[2429761.377] {Default Queue} wl_registry#2.global(5, "wl_subcompositor", 1)
[2429761.387] {Default Queue} wl_registry#2.global(6, "wl_data_device_manager", 3)
[2429761.394] {Default Queue} wl_registry#2.global(7, "zwlr_gamma_control_manager_v1", 1)
[2429761.403] {Default Queue} wl_registry#2.global(8, "zxdg_output_manager_v1", 3)
[2429761.412] {Default Queue}  -> wl_registry#2.bind(8, "zxdg_output_manager_v1", 3, new id [unknown]#5)
[2429761.421] {Default Queue} wl_registry#2.global(9, "ext_idle_notifier_v1", 1)
[2429761.428] {Default Queue} wl_registry#2.global(10, "zwp_idle_inhibit_manager_v1", 1)
[2429761.439] {Default Queue} wl_registry#2.global(11, "zwlr_layer_shell_v1", 4)
[2429761.448] {Default Queue}  -> wl_registry#2.bind(11, "zwlr_layer_shell_v1", 2, new id [unknown]#6)
[2429761.459] {Default Queue} wl_registry#2.global(12, "xdg_wm_base", 2)
[2429761.471] {Default Queue} wl_registry#2.global(13, "zwp_tablet_manager_v2", 1)
[2429761.482] {Default Queue} wl_registry#2.global(14, "org_kde_kwin_server_decoration_manager", 1)
[2429761.494] {Default Queue} wl_registry#2.global(15, "zxdg_decoration_manager_v1", 1)
[2429761.501] {Default Queue} wl_registry#2.global(16, "zwp_relative_pointer_manager_v1", 1)
[2429761.513] {Default Queue} wl_registry#2.global(17, "zwp_pointer_constraints_v1", 1)
[2429761.522] {Default Queue} wl_registry#2.global(18, "wp_presentation", 1)
[2429761.533] {Default Queue} wl_registry#2.global(19, "zwlr_output_manager_v1", 4)
[2429761.542] {Default Queue} wl_registry#2.global(20, "zwlr_output_power_manager_v1", 1)
[2429761.551] {Default Queue} wl_registry#2.global(21, "zwp_input_method_manager_v2", 1)
[2429761.559] {Default Queue} wl_registry#2.global(22, "zwp_text_input_manager_v3", 1)
[2429761.601] {Default Queue} wl_registry#2.global(23, "zwlr_foreign_toplevel_manager_v1", 3)
[2429761.609] {Default Queue} wl_registry#2.global(24, "ext_session_lock_manager_v1", 1)
[2429761.618] {Default Queue} wl_registry#2.global(25, "wp_drm_lease_device_v1", 1)
[2429761.626] {Default Queue} wl_registry#2.global(26, "zwlr_export_dmabuf_manager_v1", 1)
[2429761.634] {Default Queue} wl_registry#2.global(27, "zwlr_screencopy_manager_v1", 3)
[2429761.644] {Default Queue} wl_registry#2.global(28, "zwlr_data_control_manager_v1", 2)
[2429761.663] {Default Queue} wl_registry#2.global(29, "wp_security_context_manager_v1", 1)
[2429761.672] {Default Queue} wl_registry#2.global(30, "wp_viewporter", 1)
[2429761.683] {Default Queue} wl_registry#2.global(31, "wp_single_pixel_buffer_manager_v1", 1)
[2429761.691] {Default Queue} wl_registry#2.global(32, "wp_content_type_manager_v1", 1)
[2429761.702] {Default Queue} wl_registry#2.global(33, "wp_fractional_scale_manager_v1", 1)
[2429761.711] {Default Queue} wl_registry#2.global(34, "zxdg_exporter_v1", 1)
[2429761.722] {Default Queue} wl_registry#2.global(35, "zxdg_importer_v1", 1)
[2429761.729] {Default Queue} wl_registry#2.global(36, "zxdg_exporter_v2", 1)
[2429761.742] {Default Queue} wl_registry#2.global(37, "zxdg_importer_v2", 1)
[2429761.753] {Default Queue} wl_registry#2.global(38, "xdg_activation_v1", 1)
[2429761.763] {Default Queue} wl_registry#2.global(39, "wp_cursor_shape_manager_v1", 1)
[2429761.771] {Default Queue} wl_registry#2.global(40, "zwp_virtual_keyboard_manager_v1", 1)
[2429761.779] {Default Queue} wl_registry#2.global(41, "zwlr_virtual_pointer_manager_v1", 2)
[2429761.789] {Default Queue}  -> wl_registry#2.bind(41, "zwlr_virtual_pointer_manager_v1", 1, new id [unknown]#7)
[2429761.804] {Default Queue}  -> zwlr_virtual_pointer_manager_v1#7.create_virtual_pointer(nil, new id zwlr_virtual_pointer_v1#8)
[2429761.815] {Default Queue} wl_registry#2.global(42, "zwlr_input_inhibit_manager_v1", 1)
[2429761.824] {Default Queue} wl_registry#2.global(43, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[2429761.833] {Default Queue} wl_registry#2.global(44, "zwp_pointer_gestures_v1", 3)
[2429761.841] {Default Queue} wl_registry#2.global(45, "wl_seat", 8)
[2429761.851] {Default Queue}  -> wl_registry#2.bind(45, "wl_seat", 7, new id [unknown]#9)
[2429761.861] {Default Queue}  -> wl_seat#9.get_keyboard(new id wl_keyboard#10)
[2429761.874] {Default Queue} wl_registry#2.global(47, "zwp_primary_selection_device_manager_v1", 1)
[2429761.882] {Default Queue} wl_registry#2.global(48, "wl_output", 4)
[2429761.891] {Default Queue}  -> wl_registry#2.bind(48, "wl_output", 3, new id [unknown]#11)
[2429761.903] {Default Queue} wl_registry#2.global(49, "wl_seat", 8)
warpd: src/platform/linux/wayland/wl.c:28: handle_global: Assertion `!wl.seat' failed.
Aborted (core dumped)
```

**Comment by sonjiku** [comment]
I have modified @anpandey's overlay so you can have different packages for normal warpd, and the without-x one that you can run with `warpd-wl` instead of `warpd`:
```nix
    nixpkgs.overlays = [
        (self: super: {
            warpd-wl = (super.warpd.overrideAttrs (old: {
                pname = old.pname + "-wl";
                src = super.fetchFromGitHub {
                    owner = "rvaiya";
                    repo = "warpd";
                    rev = "01650eabf70846deed057a77ada3c0bbb6d97d6e";
                    sha256 = "sha256-61+kJvOi4oog0+tGucc1rWemdx2vp15wlluJE+1PzTs=";
                };
                postPatch = ''
                    substituteInPlace mk/linux.mk \
                    --replace-fail 'files/warpd.1.gz $(DESTDIR)$(PREFIX)/share/man/man1/' 'files/warpd.1.gz $(DESTDIR)$(PREFIX)/share/man/man1/warpd-wl.1.gz' \
                    --replace-fail '$(DESTDIR)$(PREFIX)/bin/warpd' '$(DESTDIR)$(PREFIX)/bin/warpd-wl' \
                    --replace-fail 'bin/warpd $(DESTDIR)$(PREFIX)/bin/' 'bin/warpd $(DESTDIR)$(PREFIX)/bin/warpd-wl' \
                    --replace-fail 'rm $(DESTDIR)$(PREFIX)/share/man/man1/warpd.1.gz' 'rm $(DESTDIR)$(PREFIX)/share/man/man1/warpd-wl.1.gz'
                '';
            })).override{withX = false;};
        })
    ];
```

**Comment by voronind-com** [comment]
I have the same issue with Sway 1.10 on NixOS.
```text
$ warpd -f
Starting warpd v1.3.5 (built from: effea40)
[destroyed object]: error 4: surface was destroyed before its role object
```

**Comment by sim590** [comment]
It seems like it's stuck forever here:

![Image](https://github.com/user-attachments/assets/e9720b0d-cbb0-4c1f-bda6-491b00c1da72)

If I just run the program in foreground (with `-f`) and I CTRL+C as soon as I see the error message, I end up there with this backtrace:

```
#0  0x00007ffff7af841d in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7f6e496 in wl_display_prepare_read_queue () from /usr/lib/libwayland-client.so.0
#2  0x00007ffff7f700b0 in wl_display_dispatch_queue () from /usr/lib/libwayland-client.so.0
#3  0x00005555555624d1 in surface_show (sfc=0x555555d93180, output=0x555555d2dd00)
    at src/platform/linux/wayland/surface.c:155
#4  0x0000555555563836 in init_screen () at src/platform/linux/wayland/screen.c:119
#5  0x00005555555632af in init_wl () at src/platform/linux/wayland/wl.c:91
#6  0x0000555555561282 in wl_run (loop=0x555555560474 <daemon_loop>)
    at src/platform/linux/wayland/wayland.c:32
#7  0x000055555556114a in main (argc=2, argv=0x7fffffffd0b8) at src/warpd.c:448
```

It's also possible to step your way into the code and get the same result. I don't know Wayland to comment on that further...

I'm getting this on Sway 1.10 on Archlinux and warpd `v1.3.5`.

**Comment by bogorad** [comment]
> worked for me:

worked for me as well, thank you! nixos-24.11/sway-1.10
